### ISSUE TITLE
Add support for SOTO/Horn of Maguuma

### ISSUE THREAD

**Issue by HexedHero** [Metallis/Only-Fish-Marker-Pack#2]
The fishing locations aren't marked in the Horn of Maguuma such as the areas in Primal Maguuma.

**Comment by Metallis** [comment]
Known, I just haven't had time. Gyala Delve is only partially marked too. I'll try and set aside some time here as soon as I can.

**Comment by Metallis** [comment]
Support has been added for all available maps.
